version: '3.3'
services:
  backend:
    container_name: backend
    build:
      context: ./LibrarIMTBackend
      dockerfile: DockerfileBackend
    image: librarimt-backend:latest
    ports:
      - "8080:8080"
    networks:
      - metier-network
  frontend:
    container_name: frontend
    build:
      context: FrontendLibrarIMT
      dockerfile: DockerfileFrontend
    image: librarimt-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - metier-network

networks:
  metier-network:
    driver: bridge